
name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3

       - name: Switch to gh-pages
         run: |
           git checkout -B gh-pages

       - name: Use Node.js 14.x
         uses: actions/setup-node@v3
         with:
           node-version: 14.x
           cache: 'npm'

       - name: Install dependencies and building the project
         run: | 
          npm ci
          npm run build

       - name: Commit
         run: |
          echo "Credentials..."
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          echo "Adding the public folder as the main folder in gh-pages branch..."
          git filter-branch -f --subdirectory-filter public -- gh-pages
          
          echo "Committing new changes..."
          git add .
          git commit -m ":robot: Add changes"
          
          echo "Forcing gh-pages new HEAD..."
          git push --force-with-lease

          echo "All done."
