
name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       
       - name: Switch to gh-pages
         run: |
           git checkout -B gh-pages

       - name: Use Node.js 14.x
         uses: actions/setup-node@v3
         with:
           node-version: 14.x
           cache: 'npm'

       - name: Install node dependencies
         run: npm ci

       - name: Build website
         run: npm run build

       - name: Commit
         run: |
           git filter-branch -f --subdirectory-filter public -- gh-pages
           git add .
           git commit -m ":robot: Add changes"
           git push --force-with-lease --set-upstream origin gh-pages
