
name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js 14.x
         uses: actions/setup-node@v3
         with:
           node-version: 14.x
           cache: 'npm'

       - name: Install node dependencies
         run: npm ci

       - name: Build website
         run: npm run build

       - name: Change branch
         run: |
           git fetch
           git checkout -B gh-pages
           git checkout main
           git branch -D gh-pages
           git branch gh-pages HEAD
           git config user.name github-actions
           git config user.email github-actions@github.com
           git checkout gh-pages

       - name: Search Differences
         id: search-differences
         run: |
           echo "$(git diff HEAD)"
           echo ::set-output name=differences::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

       - name: Commit
         if: steps.search-differences.outputs.differences == 'true'
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git config advice.addIgnoredFile false
           git add .
           git commit -m ":robot: Add changes"
           git push --force-with-lease --set-upstream origin gh-pages
           git filter-branch -f --subdirectory-filter public -- gh-pages
           git push --force-with-lease
